### ISSUE TITLE
Waypoint names not restaored and waypoint positions at [0, 0, 0]

### ISSUE THREAD

**Issue by Geelik** [DreadPirateAU/JEBUS#13]
Hi,

Using your script i found these issues.
Waypoint names  are not saved/restored.
Sometimes waypoint are restored at [0,0,0].

I can fix both of these issues if you accept pull request

**Comment by DreadPirateAU** [comment]
Sorry I took so long to reply, I'm not playing A3 as much these days.....

Feel free to make a pull request.....
