### ISSUE TITLE
JEBUS lacks a licence.

### ISSUE THREAD

**Issue by Drofseh** [DreadPirateAU/JEBUS#4]
I'm interested in integrating JEBUS into the mission framework of my unit.

Without a licence allowing at least redistribution this is impossible in a legal sense.

I would prefer MIT Licence, but anything that allow redistribution (and preferably modification) would be great.

Would it be possible to add such a licence to this repository?

**Comment by DreadPirateAU** [comment]
MIT Licence added.

Let me know if you have any suggestions for improving the script.
