### ISSUE TITLE
How work ?

### ISSUE THREAD

**Issue by testerfr810** [DreadPirateAU/JEBUS#6]
i try to use but, no works for me.
i try to respawn enemy planes in air( flying)
can you do video update for the new pls or how can i do ?
i place in INIT plane or INIT pilot ?
i use without trigger is that ?
and what's GAIA no UPS.sqf in folder 

i tried that

0 = [this,"FLYING", "DELAY=", [30,60]] spawn jebus_fnc_main;

ty for all :)

**Comment by DreadPirateAU** [comment]
Here's a demo mission with planes:

[https://drive.google.com/open?id=1ho7oivdkJX580Ls4qgDDaAbxuSeeilq2](url)

**Comment by testerfr810** [comment]
ty very, but when vehicle destroy no disappear lot of after on the map( no deletevehicle), i see in code but plane always on map.
ty for fast reply
:)

**Comment by DreadPirateAU** [comment]
Jebus doesn't do clean up, that's up to the mission maker.

https://community.bistudio.com/wiki/Description.ext#Corpse_.26_wreck_management
