### ISSUE TITLE
AI Spawn Height

### ISSUE THREAD

**Issue by Dutchie6101** [DreadPirateAU/JEBUS#8]
Hello mate,

Just started playing around with the script, I really like it. So thank you very much for sharing!
Question: Is there a way for AI to retain the elevation they're placed at? I have a mission with lots of elevation and on trigger activation they spawn at ground level, below the buildings.

Also I can't seem to make turrets spawn, although that is not a big deal.

Thanks again!
Dutchie

**Comment by DreadPirateAU** [comment]
I had a lot of trouble spawning units in exact positions, so I tend to spawn them in the open and use a separate script like Zenophon's House Occupy to move them inside.

With turrets, I use the vanilla Vehicle Respawn module on the turret and a jebus unit with a "GET IN NEAREST" waypoint.

**Comment by Dutchie6101** [comment]
Thanks for the reply and sorry for the late response. I tried the script you mentioned but wasn't able to make it work for this particular op. No bother, I'll definitely find a use for your script in the future.

Thanks again for all the work throughout the years
