### ISSUE TITLE
Error in fn_spawnVehicle.sqf

### ISSUE THREAD

**Issue by MrSlato** [DreadPirateAU/JEBUS#9]
Get an error on mission load when using vehicles:

`'...newVehicle addItemCargoGlobal [_x,1];} |#|forEach _vehicleItemCargo;
{_newVehicle ...'
Error foreach: Type Number, expected Array
File jebus\fnc_spawnVehicle.sqf [jebus_fnc_spawnVehicle]..., line 48`

**Comment by MrSlato** [comment]
Gone through the mission and removed all items from the vehicles thinking that might fix it. Sadly, no.

**Comment by DreadPirateAU** [comment]
Sorry, I wasn't able to recreate this error on my end. Can you provide any more details that might help me work out what's going wrong? 

Are you spawning lots of units at the same time?

**Comment by MrSlato** [comment]
I've been able to reliable replicate the issue with a simple no mods VR test. One MRAP placed down and immediate error on load. Crew refuses to spawn in the vehicle. I'll re-download JEBUS and try it again incase I've got some buggy code. Failing that I'll give you a copy of the test mission.

**Comment by DreadPirateAU** [comment]
OK, I've found the bug. My internal version was working, but the repository was wrong.

Try it again.....

**Comment by MrSlato** [comment]
Looks good now mate, no error now. Thanks for fixing it so quickly.
